export const SET_HISTORY = "SET_HISTORY"
export const EVOLVE_HISTORY = "EVOLVE_HISTORY" 
export const CLEAR_HISTORY = "CLEAR_HISTORY"

export const START_PLAYER_TURN = "START_PLAYER_TURN"
export const END_PLAYER_TERM = "END_PLAYER_TURN"
export const UPDATE_PLAYER_STATS = "UPDATE_PLAYER_STATS"

export const SET_RULES = "SET_RULES"
export const CLEAR_RULES = "CLEAR_RULES"

export const SET_DIFFICULTY = "SET_DIFFICULTY"
export const CLEAR_DIFFICULTY = "CLEAR_DIFFICULT"

export const SET_GAME = "SET_GAME"
export const CLEAR_GAME = "CLEAR_GAME"

export const GAME_RESET = "RESET"